---
- set_fact:
    elasticache_subnet_group_name: "{{ aws_resource_tag_slug.lower() }}-{{ aws_resource_env_slug.lower() }}-cache-subnet-group-by-ansible"

- name: Configure the elasticache subnet group
  elasticache_subnet_group:
    aws_access_key: "{{ aws_api_access_key }}"
    aws_secret_key: "{{ aws_api_secret_key }}"
    description: "{{ aws_resource_tag_slug + ' ' + aws_resource_env_slug + ' cache subnet group ' + aws_resource_name_suffix | trim }}"
    name: "{{ elasticache_subnet_group_name }}"
    region: "{{ aws_vpc_region }}"
    state: present
    subnets: "{{ aws_vpc_private_subnet_id_list }}"

- name: Configure an elasticache instance
  elasticache:   #  See https://docs.ansible.com/ansible/latest/modules/elasticache_instance_module.html
    aws_access_key: "{{ aws_api_access_key }}"
    aws_secret_key: "{{ aws_api_secret_key }}"
    cache_engine_version: "{{ elasticache_engine_version }}"
    # cache_parameter_group: use default
    cache_port: "{{ elasticache_port }}"
    cache_subnet_group: "{{ elasticache_subnet_group_name }}"
    engine: "{{ elasticache_engine }}"
    hard_modify: no
    name: "{{ elasticache_cluster_name }}"
    node_type: "{{ elasticache_instance_type }}"
    num_nodes: "{{ elasticache_num_nodes }}"
    region: "{{ aws_vpc_region }}"
    state: "{{ elasticache_state }}"
    security_group_ids:
      - "{{ ec2_cache_nodes_security_group_id }}"
    wait: no
    zone: "{{ elasticache_availability_zone }}"
  register: elasticache_instance_result

- debug:
    var: elasticache_instance_result
    verbosity: 1
