---
- name: 'Configure a single-node, single-cluster, single-az elasticache instance - see https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/WhatIs.Terms.html'
  elasticache:   #  See https://docs.ansible.com/ansible/latest/modules/elasticache_module.html
    aws_access_key: "{{ aws_api_access_key }}"
    aws_secret_key: "{{ aws_api_secret_key }}"
    cache_engine_version: "{{ elasticache_engine_version }}"
    # cache_parameter_group: use default
    cache_port: "{{ elasticache_port }}"
    cache_subnet_group: "{{ elasticache_subnet_group_name }}"
    engine: "{{ elasticache_engine }}"
    hard_modify: no
    name: "{{ elasticache_cluster_name }}"
    node_type: "{{ elasticache_instance_type }}"
    num_nodes: 1
    region: "{{ aws_vpc_region }}"
    state: "{{ elasticache_state }}"
    security_group_ids:
      - "{{ ec2_cache_nodes_security_group_id }}"
    wait: no
    zone: "{{ elasticache_availability_zone }}"
  register: elasticache_instance_result

- debug:
    var: elasticache_instance_result
    verbosity: 1

- name: Set redis_endpoint variable
  set_fact:
    redis_endpoint: "{{ elasticache_instance_result.elasticache.data.CacheNodes[0].Endpoint.Address  }}"

- debug:
    var: redis_endpoint
    verbosity: 1

- name: Get the current caller identity information
  aws_caller_info:
    aws_access_key: "{{ aws_api_access_key }}"
    aws_secret_key: "{{ aws_api_secret_key }}"
  register: _caller_info

- set_fact:
    elasticache_cluster_arn: "arn:aws:elasticache:{{ aws_vpc_region }}:{{ _caller_info.account }}:cluster:{{ elasticache_cluster_name }}"

- name: Tag elasticache nodes manually because the elasticache module does not yet support tagging
  command: >
    aws elasticache add-tags-to-resource
    --resource-name '{{ elasticache_cluster_arn }}'
    --tags '{{ aws_billing_tags | dict2items(key_name='Key', value_name='Value')  | to_json }}'
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_api_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_api_secret_key }}"
    AWS_DEFAULT_REGION: "{{ aws_vpc_region }}"
  when: (aws_billing_tags | length) > 0
  register: elasticache_tag_result

- debug:
    var: elasticache_tag_result
    verbosity: 1
