---
- import_tasks: ./ec2-ssh-keypair.yml
- import_tasks: ./ec2-security-groups.yml
- import_tasks: ./ec2-bastion.yml
- import_tasks: ./rds.yml
- import_tasks: ./elasticache.yml
- import_tasks: ./nfs.yml
- import_tasks: ./ec2-app-nodes.yml
- import_tasks: ./ec2-elk.yml
  when: ec2_elk_node == true
- import_tasks: ./ec2-elb.yml
