---
- import_tasks: ./ec2-ssh-keypair.yml

- import_tasks: ./ec2-security-groups.yml

- include_tasks: ./bastion.{{ bastion_provider }}.yml

- import_tasks: ./database.yml

- include_tasks: ./elasticache.yml
  when: elasticache_az_mode != 'none'

- import_tasks: ./nfs.yml

- import_tasks: ./ec2-app-nodes.yml

- include_tasks: ./ec2-elk.yml
  when: ec2_elk_node == true

- import_tasks: ./load-balancer.yml
