---
- set_fact:
    ec2_instance_pretty_name: "{{ aws_resource_tag_slug + ' ' + aws_resource_env_slug + ' EFS ' + aws_resource_name_suffix | trim }}"
    ec2_ansible_group_id: "{{ aws_resource_tag_slug.lower() }}-{{ aws_resource_env_slug.lower() }}-nfs" # this controls how many instances are launched
    efs_tags: "{{
      aws_billing_tags | combine({
        'Name': efs_name,
        'ansible-host-id': efs_name
        })
      }}"

- set_fact:
    efs_target_list_as_json: '[
      {% for subnet_id in aws_vpc_private_subnet_id_list %}
      {
      "subnet_id": "{{ subnet_id }}",
      "security_groups": ["{{ ec2_file_nodes_security_group_id }}"]
      }
      {% endfor %}
      ]'

- name: Create an elastic file system (EFS) with one mount point per private subnet
  efs:
    state: present
    region: "{{ aws_vpc_region }}"
    aws_access_key: "{{ aws_api_access_key }}"
    aws_secret_key: "{{ aws_api_secret_key }}"
    name: "{{ efs_name }}"
    tags: "{{ efs_tags }}"
    throughput_mode: "{{ efs_throughput_mode }}"
    performance_mode: "{{ efs_performance_mode }}"
    # provisioned_throughput_in_mibps: # would be reuqired if performance_mode == max_io
    wait: "{{ efs_wait }}"
    wait_timeout: "{{ efs_wait_timeout }}"
    encrypt: "{{ efs_encrypt }}"
    targets: "{{ efs_target_list_as_json }}"


  register: efs_result

- debug:
    var: efs_result
    verbosity: 1

- set_fact:
    efs_endpoint:
