---
- set_fact:
    ec2_instance_pretty_name: "{{ aws_resource_tag_slug + ' ' + aws_resource_env_slug + ' NFS ' + aws_resource_name_suffix | trim }}"
    ec2_ansible_group_id: "{{ aws_resource_tag_slug.lower() }}-{{ aws_resource_env_slug.lower() }}-nfs" # this controls how many instances are launched

- include_tasks: ./nfs.{{ nfs_provider }}-provider.yml
