---
- set_fact:
    rds_db_subnet_group_name: "{{ aws_resource_tag_slug.lower() }}-{{ aws_resource_env_slug.lower() }}-db-subnet-group-by-ansible"

- name: Configure the RDS DB subnet group
  rds_subnet_group:
    aws_access_key: "{{ aws_api_access_key }}"
    aws_secret_key: "{{ aws_api_secret_key }}"
    description: "{{ aws_resource_tag_slug + ' ' + aws_resource_env_slug + ' DB subnet group ' + aws_resource_name_suffix | trim }}"
    name: "{{ rds_db_subnet_group_name }}"
    region: "{{ aws_vpc_region }}"
    state: present
    subnets: "{{ private_subnet_result['results'] | map(attribute='subnet') | map(attribute='id') | list }}"

- import_tasks: ./rds.multi-az.yml
  when: rds_multi_az == true

- import_tasks: ./rds.single-az.yml
  when: rds_multi_az == false

- debug:
    var: rds_instance_result
    verbosity: 1
