---
- set_fact:
    rds_db_subnet_group_name: "{{ aws_resource_tag_slug.lower() }}-{{ aws_resource_env_slug.lower() }}-db-subnet-group-by-ansible"

- name: Configure the RDS DB subnet group
  rds_subnet_group:
    aws_access_key: "{{ aws_api_access_key }}"
    aws_secret_key: "{{ aws_api_secret_key }}"
    description: "{{ aws_resource_tag_slug + ' ' + aws_resource_env_slug + ' DB subnet group ' + aws_resource_name_suffix | trim }}"
    name: "{{ rds_db_subnet_group_name }}"
    region: "{{ aws_vpc_region }}"
    state: present
    subnets: "{{ private_subnet_result['results'] | map(attribute='subnet') | map(attribute='id') | list }}"

- include_tasks: ./rds.{{ rds_az_mode }}-az.yml

- name: show value for rds_instance_result
  debug:
    var: rds_instance_result
    verbosity: 1

- name: Set the deletion protection parameter via command line, since it is not yet supported by the ansible rds module
  command: >
    aws rds modify-db-instance
    --db-instance-identifier '{{ rds_db_instance_identifier }}'
    {{ rds_deletion_protection | ternary('--deletion-protection', '--no-deletion-protection') }}
    --apply-immediately
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_api_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_api_secret_key }}"
    AWS_DEFAULT_REGION: "{{ aws_vpc_region }}"
  register: rds_deletion_protection_result

- debug:
    var: rds_deletion_protection_result
    verbosity: 1
